version: 2.1
orbs:
  gradle: circleci/gradle@3.0.0
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: cimg/android:2023.04.1
    resource_class: large
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run:
                name: Bootstrap 0
                command: ./gradlew bootstrap -Pstage0
            - run:
                name: Bootstrap
                command: ./gradlew bootstrap
            - run:
                name: Check
                command: ./gradlew check
      - gradle/collect_test_results
  publish:
    working_directory: ~/code
    docker:
      - image: cimg/openjdk:17.0.8
    resource_class: large
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - deploy:
          command: |
            echo "$MAVEN_CENTRAL_SEC_RING" | base64 -d > $HOME/secring.gpg
            gpg --import --batch $HOME/secring.gpg
            ./gradlew publish -PsonatypeUsername="$SONATYPE_USERNAME" -PsonatypePassword="$SONATYPE_PASSWORD" -Psigning.keyId=34BCD878 -Psigning.password="$MAVEN_CENTRAL_KEY_PASSPHRASE" -Psigning.secretKeyRingFile=$HOME/secring.gpg -Porg.gradle.parallel=false
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          context: opensource-maven
          requires:
            - build
          filters:
            branches:
              only: main
            tags:
              only: /^v.*/