[versions]
version = "0.1.0"
junit5 = "5.9.2"

[libraries]
self = { module = "me.tatarka.gradle:central-release-publishing", version.ref = "version" }
nexus-publish = { module = "io.github.gradle-nexus:publish-plugin", version = "1.3.0" }
dokkatoo = { module = "dev.adamko.dokkatoo:dokkatoo-plugin", version = "2.0.0" }
android = { module = " com.android.tools.build:gradle-api", version = "8.1.0" }
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit5-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version = "0.27.0" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin" }